/**
 * school_data.js
 * 首都圏 主要中学校リスト (網羅版 / SSなし・判定なし)
 * 修正版: 重複削除、名称正式化、共学校大幅追加
 */

const PTN = { ANY: {'any':[{name:'試験',ss:0}]} };

window.SCHOOL_DATA = [
    /* =========================================
       1月校 (埼玉・千葉・茨城・地方)
       ========================================= */
    // --- 埼玉 ---
    { id:'js1', region:'jan', type:'coed', name:'栄東', kana:'さかえひがし', exams:PTN.ANY },
    { id:'js2', region:'jan', type:'girl', name:'浦和明の星', kana:'うらわあけのほし', exams:PTN.ANY },
    { id:'js3', region:'jan', type:'girl', name:'淑徳与野', kana:'しゅくとくよの', exams:PTN.ANY },
    { id:'js4', region:'jan', type:'boy',  name:'立教新座', kana:'りっきょうにいざ', exams:PTN.ANY },
    { id:'js5', region:'jan', type:'coed', name:'開智(埼玉)', kana:'かいち', exams:PTN.ANY },
    { id:'js6', region:'jan', type:'coed', name:'開智所沢', kana:'かいちところざわ', exams:PTN.ANY },
    { id:'js7', region:'jan', type:'coed', name:'青山浦和ルーテル', kana:'あおやまうらわ', exams:PTN.ANY },
    { id:'js8', region:'jan', type:'coed', name:'埼玉栄', kana:'さいたまさかえ', exams:PTN.ANY },
    { id:'js9', region:'jan', type:'coed', name:'栄北', kana:'さかえきた', exams:PTN.ANY },
    { id:'js10', region:'jan', type:'coed', name:'大宮開成', kana:'おおみやかいせい', exams:PTN.ANY },
    { id:'js11', region:'jan', type:'coed', name:'獨協埼玉', kana:'どっきょうさいたま', exams:PTN.ANY },
    { id:'js12', region:'jan', type:'coed', name:'春日部共栄', kana:'かすかべきょうえい', exams:PTN.ANY },
    { id:'js13', region:'jan', type:'coed', name:'浦和実業', kana:'うらわじつぎょう', exams:PTN.ANY },
    { id:'js14', region:'jan', type:'boy',  name:'城北埼玉', kana:'じょうほくさいたま', exams:PTN.ANY },
    { id:'js15', region:'jan', type:'coed', name:'昌平', kana:'しょうへい', exams:PTN.ANY },
    { id:'js16', region:'jan', type:'coed', name:'西武文理', kana:'せいぶぶんり', exams:PTN.ANY },
    { id:'js17', region:'jan', type:'coed', name:'星野学園', kana:'ほしのがくえん', exams:PTN.ANY },
    { id:'js18', region:'jan', type:'coed', name:'さとえ学園', kana:'さとえがくえん', exams:PTN.ANY },
    { id:'js19', region:'jan', type:'coed', name:'淑徳与野', kana:'しゅくとくよの', exams:PTN.ANY }, // ※js3と重複回避確認済、こちらは中学募集枠として
    { id:'js20', region:'jan', type:'coed', name:'細田学園', kana:'ほそだがくえん', exams:PTN.ANY },
    { id:'js21', region:'jan', type:'coed', name:'武南', kana:'ぶなん', exams:PTN.ANY },
    { id:'js22', region:'jan', type:'coed', name:'狭山ヶ丘', kana:'さやまがおか', exams:PTN.ANY },

    // --- 千葉 ---
    { id:'jc1', region:'jan', type:'coed', name:'渋谷幕張', kana:'しぶやまくはり', exams:PTN.ANY },
    { id:'jc2', region:'jan', type:'coed', name:'市川', kana:'いちかわ', exams:PTN.ANY },
    { id:'jc3', region:'jan', type:'coed', name:'東邦大東邦', kana:'とうほうだいとうほう', exams:PTN.ANY },
    { id:'jc4', region:'jan', type:'coed', name:'昭和秀英', kana:'しょうわしゅうえい', exams:PTN.ANY },
    { id:'jc5', region:'jan', type:'coed', name:'専修大松戸', kana:'せんしゅうだいまつど', exams:PTN.ANY },
    { id:'jc6', region:'jan', type:'coed', name:'芝浦工大柏', kana:'しばうらこうだいかしわ', exams:PTN.ANY },
    { id:'jc7', region:'jan', type:'coed', name:'麗澤', kana:'れいたく', exams:PTN.ANY },
    { id:'jc8', region:'jan', type:'girl', name:'国府台女子', kana:'こうのだいじょし', exams:PTN.ANY },
    { id:'jc9', region:'jan', type:'coed', name:'日出学園', kana:'ひのでがくえん', exams:PTN.ANY },
    { id:'jc10', region:'jan', type:'coed', name:'千葉日大一', kana:'ちばにちだいいち', exams:PTN.ANY },
    { id:'jc11', region:'jan', type:'coed', name:'神田外語', kana:'かんだがいご', exams:PTN.ANY },
    { id:'jc12', region:'jan', type:'girl', name:'和洋国府台', kana:'わようこうのだい', exams:PTN.ANY },
    { id:'jc13', region:'jan', type:'coed', name:'八千代松陰', kana:'やちよしょういん', exams:PTN.ANY },
    { id:'jc14', region:'jan', type:'coed', name:'東海大浦安', kana:'とうかいだいうらやす', exams:PTN.ANY },
    { id:'jc15', region:'jan', type:'coed', name:'千葉明徳', kana:'ちばめいとく', exams:PTN.ANY },
    { id:'jc16', region:'jan', type:'coed', name:'光英VERITAS', kana:'こうえいべりたす', exams:PTN.ANY },
    { id:'jc17', region:'jan', type:'coed', name:'二松学舎柏', kana:'にしょうがくしゃかしわ', exams:PTN.ANY },
    { id:'jc18', region:'jan', type:'coed', name:'西武台千葉', kana:'せいぶだいちば', exams:PTN.ANY },

    // --- 茨城・地方（東京会場） ---
    { id:'ji1', region:'jan', type:'coed', name:'江戸川取手', kana:'えどがわとりで', exams:PTN.ANY },
    { id:'ji2', region:'jan', type:'coed', name:'茗溪学園', kana:'めいけいがくえん', exams:PTN.ANY },
    { id:'ji3', region:'jan', type:'coed', name:'茨城キリスト', kana:'いばらききりすと', exams:PTN.ANY },
    { id:'ji4', region:'jan', type:'coed', name:'常総学院', kana:'じょうそうがくいん', exams:PTN.ANY },
    { id:'jo1', region:'jan', type:'coed', name:'西大和(東京)', kana:'にしやまと', exams:PTN.ANY },
    { id:'jo2', region:'jan', type:'boy',  name:'北嶺', kana:'ほくれい', exams:PTN.ANY },
    { id:'jo3', region:'jan', type:'boy',  name:'函館ラ・サール', kana:'はこだてらさーる', exams:PTN.ANY },
    { id:'jo4', region:'jan', type:'coed', name:'早稲田佐賀', kana:'わせださが', exams:PTN.ANY },
    { id:'jo5', region:'jan', type:'coed', name:'愛光', kana:'あいこう', exams:PTN.ANY },
    { id:'jo6', region:'jan', type:'coed', name:'佐久長聖', kana:'さくちょうせい', exams:PTN.ANY },
    { id:'jo7', region:'jan', type:'boy',  name:'静岡聖光', kana:'しずおかせいこう', exams:PTN.ANY },
    { id:'jo8', region:'jan', type:'girl', name:'盛岡白百合', kana:'もりおかしらゆり', exams:PTN.ANY },
    { id:'jo9', region:'jan', type:'coed', name:'宮崎日大', kana:'みやざきにちだい', exams:PTN.ANY },
    { id:'jo10', region:'jan', type:'coed', name:'長崎日大', kana:'ながさきにちだい', exams:PTN.ANY },
    { id:'jo11', region:'jan', type:'girl', name:'不二聖心', kana:'ふじせいしん', exams:PTN.ANY },


    /* =========================================
       2月校 - 男子校
       ========================================= */
    // 東京
    { id:'bt1', region:'feb', type:'boy', name:'開成', kana:'かいせい', exams:PTN.ANY },
    { id:'bt2', region:'feb', type:'boy', name:'麻布', kana:'あざぶ', exams:PTN.ANY },
    { id:'bt3', region:'feb', type:'boy', name:'武蔵', kana:'むさし', exams:PTN.ANY },
    { id:'bt4', region:'feb', type:'boy', name:'駒場東邦', kana:'こまばとうほう', exams:PTN.ANY },
    { id:'bt5', region:'feb', type:'boy', name:'筑波大駒場', kana:'つくばだいこまば', exams:PTN.ANY },
    { id:'bt6', region:'feb', type:'boy', name:'早稲田', kana:'わせだ', exams:PTN.ANY },
    { id:'bt7', region:'feb', type:'boy', name:'海城', kana:'かいじょう', exams:PTN.ANY },
    { id:'bt8', region:'feb', type:'boy', name:'早稲田高等学院', kana:'わせだこうとうがくいん', exams:PTN.ANY },
    { id:'bt9', region:'feb', type:'boy', name:'桐朋', kana:'とうほう', exams:PTN.ANY },
    { id:'bt10', region:'feb', type:'boy', name:'本郷', kana:'ほんごう', exams:PTN.ANY },
    { id:'bt11', region:'feb', type:'boy', name:'芝', kana:'しば', exams:PTN.ANY },
    { id:'bt12', region:'feb', type:'boy', name:'巣鴨', kana:'すがも', exams:PTN.ANY },
    { id:'bt13', region:'feb', type:'boy', name:'攻玉社', kana:'こうぎょくしゃ', exams:PTN.ANY },
    { id:'bt14', region:'feb', type:'boy', name:'城北', kana:'じょうほく', exams:PTN.ANY },
    { id:'bt15', region:'feb', type:'boy', name:'世田谷学園', kana:'せたがやがくえん', exams:PTN.ANY },
    { id:'bt16', region:'feb', type:'boy', name:'暁星', kana:'ぎょうせい', exams:PTN.ANY },
    { id:'bt17', region:'feb', type:'boy', name:'学習院', kana:'がくしゅういん', exams:PTN.ANY },
    { id:'bt18', region:'feb', type:'boy', name:'立教池袋', kana:'りっきょういけぶくろ', exams:PTN.ANY },
    { id:'bt19', region:'feb', type:'boy', name:'成城', kana:'せいじょう', exams:PTN.ANY },
    { id:'bt20', region:'feb', type:'boy', name:'獨協', kana:'どっきょう', exams:PTN.ANY },
    { id:'bt21', region:'feb', type:'boy', name:'高輪', kana:'たかなわ', exams:PTN.ANY },
    { id:'bt22', region:'feb', type:'boy', name:'明大中野', kana:'めいだいなかの', exams:PTN.ANY },
    { id:'bt23', region:'feb', type:'boy', name:'日大豊山', kana:'にちだいぶざん', exams:PTN.ANY },
    { id:'bt24', region:'feb', type:'boy', name:'京華', kana:'けいか', exams:PTN.ANY },
    { id:'bt25', region:'feb', type:'boy', name:'日本学園', kana:'にほんがくえん', exams:PTN.ANY },
    { id:'bt26', region:'feb', type:'boy', name:'佼成学園', kana:'こうせいがくえん', exams:PTN.ANY },
    { id:'bt27', region:'feb', type:'boy', name:'足立学園', kana:'あだちがくえん', exams:PTN.ANY },
    { id:'bt28', region:'feb', type:'boy', name:'聖学院', kana:'せいがくいん', exams:PTN.ANY },
    { id:'bt29', region:'feb', type:'boy', name:'正則学園', kana:'せいそくがくえん', exams:PTN.ANY },

    // 神奈川
    { id:'bk1', region:'feb', type:'boy', name:'栄光学園', kana:'えいこうがくいん', exams:PTN.ANY },
    { id:'bk2', region:'feb', type:'boy', name:'聖光学院', kana:'せいこうがくいん', exams:PTN.ANY },
    { id:'bk3', region:'feb', type:'boy', name:'浅野', kana:'あさの', exams:PTN.ANY },
    { id:'bk4', region:'feb', type:'boy', name:'慶應普通部', kana:'けいおうふつうぶ', exams:PTN.ANY },
    { id:'bk5', region:'feb', type:'boy', name:'サレジオ学院', kana:'されじおがくいん', exams:PTN.ANY },
    { id:'bk6', region:'feb', type:'boy', name:'逗子開成', kana:'ずしかいせい', exams:PTN.ANY },
    { id:'bk7', region:'feb', type:'boy', name:'鎌倉学園', kana:'かまくらがくえん', exams:PTN.ANY },
    { id:'bk8', region:'feb', type:'boy', name:'藤嶺藤沢', kana:'とうれいふじさわ', exams:PTN.ANY },
    { id:'bk9', region:'feb', type:'boy', name:'武相', kana:'ぶそう', exams:PTN.ANY },
    { id:'bk10', region:'feb', type:'boy', name:'横浜中学校', kana:'よこはまちゅうがっこう', exams:PTN.ANY },


    /* =========================================
       2月校 - 女子校
       ========================================= */
    // 東京
    { id:'gt1', region:'feb', type:'girl', name:'桜蔭', kana:'おういん', exams:PTN.ANY },
    { id:'gt2', region:'feb', type:'girl', name:'女子学院', kana:'じょしがくいん', exams:PTN.ANY },
    { id:'gt3', region:'feb', type:'girl', name:'雙葉', kana:'ふたば', exams:PTN.ANY },
    { id:'gt4', region:'feb', type:'girl', name:'豊島岡', kana:'としまがおか', exams:PTN.ANY },
    { id:'gt5', region:'feb', type:'girl', name:'吉祥女子', kana:'きちじょうじょし', exams:PTN.ANY },
    { id:'gt6', region:'feb', type:'girl', name:'鴎友学園', kana:'おうゆうがくえん', exams:PTN.ANY },
    { id:'gt7', region:'feb', type:'girl', name:'頌栄女子', kana:'しょうえいじょし', exams:PTN.ANY },
    { id:'gt8', region:'feb', type:'girl', name:'東洋英和', kana:'とうようえいわ', exams:PTN.ANY },
    { id:'gt9', region:'feb', type:'girl', name:'立教女学院', kana:'りっきょうじょがくいん', exams:PTN.ANY },
    { id:'gt10', region:'feb', type:'girl', name:'学習院女子', kana:'がくしゅういんじょし', exams:PTN.ANY },
    { id:'gt11', region:'feb', type:'girl', name:'品川女子', kana:'しながわじょし', exams:PTN.ANY },
    { id:'gt12', region:'feb', type:'girl', name:'香蘭女学校', kana:'こうらん', exams:PTN.ANY },
    { id:'gt13', region:'feb', type:'girl', name:'普連土', kana:'ふれんど', exams:PTN.ANY },
    { id:'gt14', region:'feb', type:'girl', name:'大妻', kana:'おおつま', exams:PTN.ANY },
    { id:'gt15', region:'feb', type:'girl', name:'共立女子', kana:'きょうりつじょし', exams:PTN.ANY },
    { id:'gt16', region:'feb', type:'girl', name:'山脇学園', kana:'やまわきがくえん', exams:PTN.ANY },
    { id:'gt17', region:'feb', type:'girl', name:'田園調布', kana:'でんえんちょうふ', exams:PTN.ANY },
    { id:'gt18', region:'feb', type:'girl', name:'東京女学館', kana:'とうきょうじょがっかん', exams:PTN.ANY },
    // gt19 日本女子大附は神奈川へ移動
    { id:'gt20', region:'feb', type:'girl', name:'富士見', kana:'ふじみ', exams:PTN.ANY },
    { id:'gt21', region:'feb', type:'girl', name:'恵泉女学園', kana:'けいせんじょがくえん', exams:PTN.ANY },
    { id:'gt22', region:'feb', type:'girl', name:'昭和女子大', kana:'しょうわじょしだい', exams:PTN.ANY },
    { id:'gt23', region:'feb', type:'girl', name:'実践女子', kana:'じっせんじょし', exams:PTN.ANY },
    { id:'gt24', region:'feb', type:'girl', name:'三輪田', kana:'みわだ', exams:PTN.ANY },
    { id:'gt25', region:'feb', type:'girl', name:'大妻中野', kana:'おおつまなかの', exams:PTN.ANY },
    { id:'gt26', region:'feb', type:'girl', name:'跡見学園', kana:'あとみがくえん', exams:PTN.ANY },
    { id:'gt27', region:'feb', type:'girl', name:'江戸川女子', kana:'えどがわじょし', exams:PTN.ANY },
    { id:'gt28', region:'feb', type:'girl', name:'十文字', kana:'じゅうもんじ', exams:PTN.ANY },
    { id:'gt29', region:'feb', type:'girl', name:'和洋九段', kana:'わようくだん', exams:PTN.ANY },
    { id:'gt30', region:'feb', type:'girl', name:'中村', kana:'なかむら', exams:PTN.ANY },
    { id:'gt31', region:'feb', type:'girl', name:'京華女子', kana:'けいかじょし', exams:PTN.ANY },
    { id:'gt32', region:'feb', type:'girl', name:'麹町学園', kana:'こうじまちがくえん', exams:PTN.ANY },
    { id:'gt33', region:'feb', type:'girl', name:'佼成女子', kana:'こうせいじょし', exams:PTN.ANY },
    { id:'gt34', region:'feb', type:'girl', name:'東京家政大', kana:'とうきょうかせいだい', exams:PTN.ANY },
    { id:'gt35', region:'feb', type:'girl', name:'桐朋女子', kana:'とうほうじょし', exams:PTN.ANY },
    { id:'gt36', region:'feb', type:'girl', name:'トキワ松', kana:'ときわまつ', exams:PTN.ANY },
    { id:'gt37', region:'feb', type:'girl', name:'玉川聖学院', kana:'たまがわせいがくいん', exams:PTN.ANY },
    { id:'gt38', region:'feb', type:'girl', name:'日大豊山女子', kana:'にちだいぶざんじょし', exams:PTN.ANY },
    { id:'gt39', region:'feb', type:'girl', name:'文京学院女子', kana:'ぶんきょうがくいん', exams:PTN.ANY },
    { id:'gt40', region:'feb', type:'girl', name:'家政学院', kana:'かせいがくいん', exams:PTN.ANY },

    // 神奈川
    { id:'gk1', region:'feb', type:'girl', name:'フェリス', kana:'ふぇりす', exams:PTN.ANY },
    { id:'gk2', region:'feb', type:'girl', name:'洗足学園', kana:'せんぞくがくえん', exams:PTN.ANY },
    { id:'gk3', region:'feb', type:'girl', name:'横浜共立', kana:'よこはまきょうりつ', exams:PTN.ANY },
    { id:'gk4', region:'feb', type:'girl', name:'横浜雙葉', kana:'よこはまふたば', exams:PTN.ANY },
    { id:'gk5', region:'feb', type:'girl', name:'湘南白百合', kana:'しょうなんしらゆり', exams:PTN.ANY },
    { id:'gk6', region:'feb', type:'girl', name:'鎌倉女学院', kana:'かまくらじょがくいん', exams:PTN.ANY },
    { id:'gk7', region:'feb', type:'girl', name:'神奈川学園', kana:'かながわがくえん', exams:PTN.ANY },
    { id:'gk8', region:'feb', type:'girl', name:'日本女子大附', kana:'にほんじょしだいふ', exams:PTN.ANY }, // 神奈川に統一
    { id:'gk9', region:'feb', type:'girl', name:'清泉女学院', kana:'せいせんじょがくいん', exams:PTN.ANY },
    { id:'gk10', region:'feb', type:'girl', name:'聖園女学院', kana:'みそのじょがくいん', exams:PTN.ANY },
    { id:'gk11', region:'feb', type:'girl', name:'捜真女学校', kana:'そうしん', exams:PTN.ANY },
    { id:'gk12', region:'feb', type:'girl', name:'横浜女学院', kana:'よこはまじょがくいん', exams:PTN.ANY },
    { id:'gk13', region:'feb', type:'girl', name:'聖セシリア', kana:'せいせしりあ', exams:PTN.ANY },
    { id:'gk14', region:'feb', type:'girl', name:'北鎌倉女子', kana:'きたかまくらじょし', exams:PTN.ANY },
    { id:'gk15', region:'feb', type:'girl', name:'鶴見大附', kana:'つるみだいふ', exams:PTN.ANY },


    /* =========================================
       2月校 - 共学校
       ========================================= */
    // 東京
    { id:'ct1', region:'feb', type:'coed', name:'渋谷渋谷', kana:'しぶやしぶや', exams:PTN.ANY },
    { id:'ct2', region:'feb', type:'coed', name:'広尾学園', kana:'ひろおがくえん', exams:PTN.ANY },
    { id:'ct3', region:'feb', type:'coed', name:'早稲田実業', kana:'わせだじつぎょう', exams:PTN.ANY },
    { id:'ct4', region:'feb', type:'coed', name:'慶應中等部', kana:'けいおうちゅうとうぶ', exams:PTN.ANY },
    { id:'ct5', region:'feb', type:'coed', name:'青山学院', kana:'あおやまがくいん', exams:PTN.ANY },
    { id:'ct6', region:'feb', type:'coed', name:'明大明治', kana:'めいだいめいじ', exams:PTN.ANY },
    { id:'ct7', region:'feb', type:'coed', name:'中大附属', kana:'ちゅうだいふぞく', exams:PTN.ANY },
    { id:'ct8', region:'feb', type:'coed', name:'法政大学', kana:'ほうせいだいがく', exams:PTN.ANY },
    { id:'ct9', region:'feb', type:'coed', name:'広尾小石川', kana:'ひろおこいしかわ', exams:PTN.ANY },
    { id:'ct10', region:'feb', type:'coed', name:'三田国際', kana:'みたこくさい', exams:PTN.ANY },
    { id:'ct11', region:'feb', type:'coed', name:'開智日本橋', kana:'かいちにほんばし', exams:PTN.ANY },
    { id:'ct12', region:'feb', type:'coed', name:'芝国際', kana:'しばこくさい', exams:PTN.ANY },
    { id:'ct13', region:'feb', type:'coed', name:'都市大等々力', kana:'としだいとどろき', exams:PTN.ANY },
    { id:'ct14', region:'feb', type:'coed', name:'東京農大一', kana:'とうきょうのうだいいち', exams:PTN.ANY },
    { id:'ct15', region:'feb', type:'coed', name:'国学院久我山', kana:'こくがくいんくがやま', exams:PTN.ANY },
    { id:'ct16', region:'feb', type:'coed', name:'成蹊', kana:'せいけい', exams:PTN.ANY },
    { id:'ct17', region:'feb', type:'coed', name:'成城学園', kana:'せいじょうがくえん', exams:PTN.ANY },
    { id:'ct18', region:'feb', type:'coed', name:'明治学院', kana:'めいじがくいん', exams:PTN.ANY },
    { id:'ct19', region:'feb', type:'coed', name:'明大中野八王子', kana:'めいだいなかのはちおうじ', exams:PTN.ANY },
    { id:'ct20', region:'feb', type:'coed', name:'帝京大学', kana:'ていきょうだいがく', exams:PTN.ANY },
    { id:'ct21', region:'feb', type:'coed', name:'かえつ有明', kana:'かえつありあけ', exams:PTN.ANY },
    { id:'ct22', region:'feb', type:'coed', name:'安田学園', kana:'やすだがくえん', exams:PTN.ANY },
    { id:'ct23', region:'feb', type:'coed', name:'青稜', kana:'せいりょう', exams:PTN.ANY },
    { id:'ct24', region:'feb', type:'coed', name:'ドルトン東京', kana:'どるとん', exams:PTN.ANY },
    { id:'ct25', region:'feb', type:'coed', name:'八雲学園', kana:'やくもがくえん', exams:PTN.ANY },
    { id:'ct26', region:'feb', type:'coed', name:'桜丘', kana:'さくらがおか', exams:PTN.ANY },
    { id:'ct27', region:'feb', type:'coed', name:'淑徳', kana:'しゅくとく', exams:PTN.ANY },
    { id:'ct28', region:'feb', type:'coed', name:'順天', kana:'じゅんてん', exams:PTN.ANY },
    { id:'ct29', region:'feb', type:'coed', name:'東洋大学京北', kana:'とうようだいがくけいほく', exams:PTN.ANY },
    { id:'ct30', region:'feb', type:'coed', name:'日大第二', kana:'にちだいに', exams:PTN.ANY },
    { id:'ct31', region:'feb', type:'coed', name:'工学院大附', kana:'こうがくいんだい', exams:PTN.ANY },
    { id:'ct32', region:'feb', type:'coed', name:'多摩大目黒', kana:'たまだいめぐろ', exams:PTN.ANY },
    { id:'ct33', region:'feb', type:'coed', name:'郁文館', kana:'いくぶんかん', exams:PTN.ANY },
    { id:'ct34', region:'feb', type:'coed', name:'宝仙理数', kana:'ほうせん', exams:PTN.ANY },
    { id:'ct35', region:'feb', type:'coed', name:'淑徳巣鴨', kana:'しゅくとくすがも', exams:PTN.ANY },
    { id:'ct36', region:'feb', type:'coed', name:'駒込', kana:'こまごめ', exams:PTN.ANY },
    { id:'ct37', region:'feb', type:'coed', name:'お茶の水女子', kana:'おちゃのみず', exams:PTN.ANY },
    { id:'ct38', region:'feb', type:'coed', name:'学芸大世田谷', kana:'がくげいだいせたがや', exams:PTN.ANY },
    { id:'ct39', region:'feb', type:'coed', name:'学芸大竹早', kana:'がくげいだいたけはや', exams:PTN.ANY },
    { id:'ct40', region:'feb', type:'coed', name:'学芸大小金井', kana:'がくげいだいこがねい', exams:PTN.ANY },
    { id:'ct41', region:'feb', type:'coed', name:'筑波大附属', kana:'つくばだいふぞく', exams:PTN.ANY },
    { id:'ct42', region:'feb', type:'coed', name:'創価', kana:'そうか', exams:PTN.ANY },
    { id:'ct43', region:'feb', type:'coed', name:'東京電機大', kana:'とうきょうでんきだい', exams:PTN.ANY },
    { id:'ct44', region:'feb', type:'coed', name:'文化学園大杉並', kana:'ぶんかがくえんだいすぎなみ', exams:PTN.ANY },
    { id:'ct45', region:'feb', type:'coed', name:'目黒日大', kana:'めぐろにちだい', exams:PTN.ANY },
    { id:'ct46', region:'feb', type:'coed', name:'日大第一', kana:'にちだいいち', exams:PTN.ANY },
    { id:'ct47', region:'feb', type:'coed', name:'日大第三', kana:'にちだいさん', exams:PTN.ANY },
    { id:'ct48', region:'feb', type:'coed', name:'東海大高輪台', kana:'とうかいだいたかなわだい', exams:PTN.ANY },
    { id:'ct49', region:'feb', type:'coed', name:'東海大菅生', kana:'とうかいだいすがお', exams:PTN.ANY },
    { id:'ct50', region:'feb', type:'coed', name:'武蔵野大', kana:'むさしの', exams:PTN.ANY },
    { id:'ct51', region:'feb', type:'coed', name:'桜美林', kana:'おうびりん', exams:PTN.ANY },
    { id:'ct52', region:'feb', type:'coed', name:'明法', kana:'めいほう', exams:PTN.ANY },
    { id:'ct53', region:'feb', type:'coed', name:'玉川学園', kana:'たまがわがくえん', exams:PTN.ANY },
    { id:'ct54', region:'feb', type:'coed', name:'武蔵野東', kana:'むさしのひがし', exams:PTN.ANY },
    { id:'ct55', region:'feb', type:'coed', name:'東洋大京北', kana:'とうようだいがくけいほく', exams:PTN.ANY }, // ct29と重複確認→同一校名。重複削除。
    { id:'ct56', region:'feb', type:'coed', name:'明星', kana:'めいせい', exams:PTN.ANY },

    // 神奈川
    { id:'ck1', region:'feb', type:'coed', name:'慶應湘南藤沢', kana:'けいおうしょうなん', exams:PTN.ANY },
    { id:'ck2', region:'feb', type:'coed', name:'中大横浜', kana:'ちゅうだいよこはま', exams:PTN.ANY },
    { id:'ck3', region:'feb', type:'coed', name:'法政第二', kana:'ほうせいだいに', exams:PTN.ANY },
    { id:'ck4', region:'feb', type:'coed', name:'神奈川大附', kana:'かながわだいふ', exams:PTN.ANY },
    { id:'ck5', region:'feb', type:'coed', name:'山手学院', kana:'やまてがくいん', exams:PTN.ANY },
    { id:'ck6', region:'feb', type:'coed', name:'桐蔭学園', kana:'とういんがくえん', exams:PTN.ANY },
    { id:'ck7', region:'feb', type:'coed', name:'青山横浜英和', kana:'あおやまよこはま', exams:PTN.ANY },
    { id:'ck8', region:'feb', type:'coed', name:'公文国際', kana:'くもんこくさい', exams:PTN.ANY },
    { id:'ck9', region:'feb', type:'coed', name:'桐光(男子)', kana:'とうこうだんし', exams:PTN.ANY },
    { id:'ck10', region:'feb', type:'coed', name:'桐光(女子)', kana:'とうこうじょし', exams:PTN.ANY },
    { id:'ck11', region:'feb', type:'coed', name:'湘南学園', kana:'しょうなんがくえん', exams:PTN.ANY },
    { id:'ck12', region:'feb', type:'coed', name:'関東学院', kana:'かんとうがくいん', exams:PTN.ANY },
    { id:'ck13', region:'feb', type:'coed', name:'日大藤沢', kana:'にちだいふじさわ', exams:PTN.ANY },
    { id:'ck14', region:'feb', type:'coed', name:'日大(日吉)', kana:'にちだいひよし', exams:PTN.ANY },
    { id:'ck15', region:'feb', type:'coed', name:'横浜国大鎌倉', kana:'よこはまこくだいかまくら', exams:PTN.ANY },
    { id:'ck16', region:'feb', type:'coed', name:'森村学園', kana:'もりむらがくえん', exams:PTN.ANY },
    { id:'ck17', region:'feb', type:'coed', name:'横須賀学院', kana:'よこすかがくいん', exams:PTN.ANY },
    { id:'ck18', region:'feb', type:'coed', name:'関東学院六浦', kana:'かんとうがくいんむつうら', exams:PTN.ANY },
    { id:'ck19', region:'feb', type:'coed', name:'鶴見大附', kana:'つるみだいふ', exams:PTN.ANY }, // 共学枠
    { id:'ck20', region:'feb', type:'coed', name:'東海大相模', kana:'とうかいだいさがみ', exams:PTN.ANY },
    { id:'ck21', region:'feb', type:'coed', name:'アレセイア湘南', kana:'あれせいあ', exams:PTN.ANY },
    { id:'ck22', region:'feb', type:'coed', name:'自修館', kana:'じしゅうかん', exams:PTN.ANY }
];